title = 'Ecology Games'

contentDir = 'content/en'
languageName = 'English'
languageCode = 'en-US'

copyright = ''

weight = 1

[params]
    author = 'Paidia'
    description = 'A place to find links to and news about ecology games.'